[tool.poetry]
name = "seefretboard"
version = "0.1.0"
description = ""
authors = ["LindaRZhang <ronglindaz@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
