[tool.poetry]
name = "seefretboard"
version = "0.0.9.7"
description = ""
authors = ["LindaRZhang <ronglindaz@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
